name: cd-pipeline-operator
namespace: ""
platform: "openshift"
cdPipelineName: ""
cdPipelineStageName: ""
dnsWildcard: ""
database:
  required: false
ingress:
  required: false
image:
  name: cd-pipeline-operator-master
  version: latest