{{- if eq .Values.platform "openshift" -}}
apiVersion: authorization.openshift.io/v1
kind: ClusterRole
metadata:
  annotations:
    openshift.io/description: Role for cd-pipeline-operator-edp service account
    openshift.io/reconcile-protect: "false"
  name: {{ .Values.name }}-{{ .Values.namespace }}-clusterrole
rules:
- apiGroups:
    - '*'
  attributeRestrictions: null
  resources:
    - securitycontextconstraints
  verbs:
    - patch
    - update
    - delete
    - get
    - list
    - create
- apiGroups:
    - '*'
  attributeRestrictions: null
  resources:
    - cdpipelines
    - cdpipelines/finalizers
    - jenkinsfolders
    - jenkinsfolders/finalizers
    - jenkinsfolders/status
    - jenkinsjobs
    - jenkinsjobs/finalizers
    - jenkinsjobs/status
    - codebases
    - codebases/finalizers
    - codebasebranches
    - codebasebranches/finalizers
    - stages
    - stages/finalizers
    - stages/status
  verbs:
    - '*'
{{ end }}
