apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: cd-pipeline-operator
roleRef:
  kind: ClusterRole
  apiGroup: rbac.authorization.k8s.io
  name: edp-deploy-role
subjects:
  - kind: ServiceAccount
    name: edp
    namespace: {{ .Values.namespace }}
# userNames:
#   - system:serviceaccount:{{ .Values.namespace }}:edp